source 'https://rubygems.org'

# specify ruby version for heroku
ruby '2.2.3'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use pg as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use bootstrap-sass for the actual bootstrap css/sass
gem 'bootstrap-sass', '~> 3.3.5'
# Use twitter-bootstrap-rails only for the helpers and generators scripts
gem 'twitter-bootstrap-rails', '~> 3.2.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use RestClient for RESTful requests
gem 'rest-client'
gem 'coach_client', '~> 0.1.0',
  git: 'https://github.com/jungomi/coach_client', branch: 'stable'

# Use ransack to build search functionality
gem 'ransack', '~> 1.7.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem "font-awesome-rails"

gem 'geocoder'
gem 'gmaps4rails'
gem 'ice_cube'
gem 'recurring_select'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'
gem 'bootstrap-timepicker-rails', require: 'bootstrap-timepicker-rails',
    git: 'https://github.com/tispratik/bootstrap-timepicker-rails.git',
    ref: 'eb489926214bc2ffb9f61ac0638d758e7a950826'
gem 'validates_timeliness', '~> 3.0'
gem 'cloudinary'
gem 'carrierwave'

gem 'acts_as_votable', git: 'https://github.com/ryanto/acts_as_votable.git', ref: '9ded371ec0720d07fa7a169109da05c835a2cb51'

gem 'social-share-button', '~> 0.1.6'
gem "bootstrap-switch-rails"
# Used to remember bootstrap switch state
gem 'js_cookie_rails', '~> 1.0'

# Google calendar
gem 'google-api-client', '0.9.pre3', require: 'google/apis/calendar_v3'
# Google omniauth authentication
gem 'omniauth-google-oauth2',
  git: 'https://github.com/zquestz/omniauth-google-oauth2', branch: 'master'
# Facebook omniauth for profile-linking
gem 'omniauth-facebook', '~> 3.0'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'
  # Set environment variables in .env file
  gem 'dotenv-rails', '~> 2.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

